-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-09-12 09:29:17 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
-- studentid: 34165479
-- student name: Akshit Mehdiratta

SET ECHO ON
SPOOL prop_rental_schema_output.txt


DROP TABLE damage CASCADE CONSTRAINTS;

DROP TABLE maintenance CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE payment CASCADE CONSTRAINTS;

DROP TABLE paymethod CASCADE CONSTRAINTS;

DROP TABLE property CASCADE CONSTRAINTS;

DROP TABLE rent CASCADE CONSTRAINTS;

DROP TABLE tenant CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE damage (
    dam_no            NUMBER(7) NOT NULL,
    dam_datetime      DATE NOT NULL,
    dam_cost          NUMBER(7) NOT NULL,
    dam_type          VARCHAR2(50) NOT NULL,
    rent_agreement_no NUMBER(9) NOT NULL,
    pay_no            NUMBER(7)
);

COMMENT ON COLUMN damage.dam_no IS
    'Damage number';

COMMENT ON COLUMN damage.dam_datetime IS
    'date and time of damage';

COMMENT ON COLUMN damage.dam_cost IS
    'cost of damage';

COMMENT ON COLUMN damage.dam_type IS
    'type of damage';

COMMENT ON COLUMN damage.rent_agreement_no IS
    'rent agreement number';

COMMENT ON COLUMN damage.pay_no IS
    'payment number';

CREATE UNIQUE INDEX damage__idx ON
    damage (
        pay_no
    ASC );

ALTER TABLE damage ADD CONSTRAINT damage_pk PRIMARY KEY ( dam_no );

CREATE TABLE maintenance (
    prop_no1       NUMBER(7) NOT NULL,
    maint_desc     VARCHAR2(50),
    maint_datetime DATE NOT NULL,
    maint_cost     NUMBER(7) NOT NULL
);

COMMENT ON COLUMN maintenance.prop_no1 IS
    'property number';

COMMENT ON COLUMN maintenance.maint_desc IS
    'maintenence description';

COMMENT ON COLUMN maintenance.maint_datetime IS
    'maintanence date and time';

COMMENT ON COLUMN maintenance.maint_cost IS
    'maintanence cost';

ALTER TABLE maintenance ADD CONSTRAINT maintenance_pk PRIMARY KEY ( maint_datetime,
                                                                    prop_no1 );

CREATE TABLE owner (
    owner_no      NUMBER(7) NOT NULL,
    owner_givname VARCHAR2(50),
    owner_famname VARCHAR2(50),
    owner_address VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN owner.owner_no IS
    'owner number';

COMMENT ON COLUMN owner.owner_givname IS
    'owner given name';

COMMENT ON COLUMN owner.owner_famname IS
    'owner family name';

COMMENT ON COLUMN owner.owner_address IS
    'owner address';

ALTER TABLE owner ADD CONSTRAINT customer_pk PRIMARY KEY ( owner_no );

CREATE TABLE payment (
    pay_no             NUMBER(7) NOT NULL,
    pay_date           DATE NOT NULL,
    pay_type           VARCHAR2(50) NOT NULL,
    pay_amount         NUMBER(10) NOT NULL,
    pay_paid_by        VARCHAR2(50) NOT NULL,
    rent_agreement_no1 NUMBER(9) NOT NULL,
    pay_paidby         VARCHAR2(7) NOT NULL
);

ALTER TABLE payment
    ADD CONSTRAINT chk_pay_type CHECK ( pay_type IN ( 'B', 'D', 'R' ) );

COMMENT ON COLUMN payment.pay_no IS
    'payment number';

COMMENT ON COLUMN payment.pay_date IS
    'payment date';

COMMENT ON COLUMN payment.pay_type IS
    'payment type';

COMMENT ON COLUMN payment.pay_amount IS
    'amount';

COMMENT ON COLUMN payment.pay_paid_by IS
    'paid by';

COMMENT ON COLUMN payment.rent_agreement_no1 IS
    'rent agreement number';

COMMENT ON COLUMN payment.pay_paidby IS
    'paymethod_id';

ALTER TABLE payment ADD CONSTRAINT payment_pk PRIMARY KEY ( pay_no );

CREATE TABLE paymethod (
    paymethod_id   VARCHAR2(7) NOT NULL,
    paymethod_name VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN paymethod.paymethod_id IS
    'paymethod_id';

COMMENT ON COLUMN paymethod.paymethod_name IS
    'pay method type';

ALTER TABLE paymethod ADD CONSTRAINT paymethod_pk PRIMARY KEY ( paymethod_id );

CREATE TABLE property (
    prop_no      NUMBER(7) NOT NULL,
    prop_address VARCHAR2(50) NOT NULL,
    prop_value   NUMBER(15) NOT NULL,
    owner_no1    NUMBER(7) NOT NULL
);

COMMENT ON COLUMN property.prop_no IS
    'property number';

COMMENT ON COLUMN property.prop_address IS
    'property address';

COMMENT ON COLUMN property.prop_value IS
    'value of property';

COMMENT ON COLUMN property.owner_no1 IS
    'owner number';

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( prop_no );

CREATE TABLE rent (
    rent_agreement_no NUMBER(9) NOT NULL,
    rent_lease_start  DATE NOT NULL,
    rent_weekly_rate  NUMBER(7) NOT NULL,
    rent_bond         DATE NOT NULL,
    rent_lease_period DATE NOT NULL,
    prop_no           NUMBER(7) NOT NULL,
    tenant_no1        NUMBER(7) NOT NULL
);

COMMENT ON COLUMN rent.rent_agreement_no IS
    'rent agreement number';

COMMENT ON COLUMN rent.rent_lease_start IS
    'start date';

COMMENT ON COLUMN rent.rent_weekly_rate IS
    'weekly rate for rent';

COMMENT ON COLUMN rent.rent_bond IS
    'bond';

COMMENT ON COLUMN rent.rent_lease_period IS
    'lease period';

COMMENT ON COLUMN rent.prop_no IS
    'property number';

COMMENT ON COLUMN rent.tenant_no1 IS
    'tenant number';

ALTER TABLE rent ADD CONSTRAINT rent_pk PRIMARY KEY ( rent_agreement_no );

CREATE TABLE tenant (
    tenant_no        NUMBER(7) NOT NULL,
    tenant_givname   VARCHAR2(50),
    tenant_givname_1 VARCHAR2(50),
    tenant_address   VARCHAR2(50) NOT NULL,
    tenant_phone     NUMBER(10) NOT NULL
);

COMMENT ON COLUMN tenant.tenant_no IS
    'tenant number';

COMMENT ON COLUMN tenant.tenant_givname IS
    'tenant given name';

COMMENT ON COLUMN tenant.tenant_givname_1 IS
    'tenant family name';

COMMENT ON COLUMN tenant.tenant_address IS
    'address of tenant';

COMMENT ON COLUMN tenant.tenant_phone IS
    'tenant phone number';

ALTER TABLE tenant ADD CONSTRAINT tenant_pk PRIMARY KEY ( tenant_no );

ALTER TABLE damage
    ADD CONSTRAINT damage_pay FOREIGN KEY ( pay_no )
        REFERENCES payment ( pay_no );

ALTER TABLE payment
    ADD CONSTRAINT paymethod_pay FOREIGN KEY ( pay_paidby )
        REFERENCES paymethod ( paymethod_id );

ALTER TABLE rent
    ADD CONSTRAINT prop_rent FOREIGN KEY ( prop_no )
        REFERENCES property ( prop_no );

ALTER TABLE maintenance
    ADD CONSTRAINT property_maint FOREIGN KEY ( prop_no1 )
        REFERENCES property ( prop_no );

ALTER TABLE property
    ADD CONSTRAINT relation_3 FOREIGN KEY ( owner_no1 )
        REFERENCES owner ( owner_no );

ALTER TABLE damage
    ADD CONSTRAINT rent_damage FOREIGN KEY ( rent_agreement_no )
        REFERENCES rent ( rent_agreement_no );

ALTER TABLE payment
    ADD CONSTRAINT rent_pay FOREIGN KEY ( rent_agreement_no1 )
        REFERENCES rent ( rent_agreement_no );

ALTER TABLE rent
    ADD CONSTRAINT tenant_rent FOREIGN KEY ( tenant_no1 )
        REFERENCES tenant ( tenant_no );

CREATE OR REPLACE TRIGGER fkntm_payment BEFORE
    UPDATE OF pay_paidby ON payment
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table PAYMENT is violated'
    );
END;
/

SPOOL off
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
