--student id: 34165479
--student name: Akshit Mehdiratta
-- Capture run of script in file called custorders_schema_output.txt set echo on

set echo on
SPOOL custorders_schema_output.txt

-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-09-01 17:34:03 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE orderline CASCADE CONSTRAINTS;

DROP TABLE orders CASCADE CONSTRAINTS;

DROP TABLE product CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE customer (
    cust_no      NUMBER(7) NOT NULL,
    cust_name    VARCHAR2(50) NOT NULL,
    cust_address VARCHAR2(50) NOT NULL,
    cust_phone   CHAR(10),
    cust_level   CHAR(1) NOT NULL
);

ALTER TABLE customer
    ADD CONSTRAINT chk_cust_level CHECK ( cust_level IN ( 'B', 'G', 'S' ) );

COMMENT ON COLUMN customer.cust_no IS
    'customer number';

COMMENT ON COLUMN customer.cust_name IS
    'customer name';

COMMENT ON COLUMN customer.cust_address IS
    'customer address';

COMMENT ON COLUMN customer.cust_level IS
    'Customer level based in spending - Gold: G, Silver: S, Bronze: B)';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( cust_no );

CREATE TABLE orderline (
    order_no   NUMBER(7) NOT NULL,
    product_id NUMBER NOT NULL
);

COMMENT ON COLUMN orderline.order_no IS
    'order number';

ALTER TABLE orderline ADD CONSTRAINT orderline_pk PRIMARY KEY ( order_no );

CREATE TABLE orders (
    order_no   NUMBER(7) NOT NULL,
    order_date DATE NOT NULL,
    cust_no    NUMBER(7) NOT NULL
);

COMMENT ON COLUMN orders.order_no IS
    'order number';

COMMENT ON COLUMN orders.order_date IS
    'order date';

COMMENT ON COLUMN orders.cust_no IS
    'customer number';

ALTER TABLE orders ADD CONSTRAINT orders_pk PRIMARY KEY ( order_no );

CREATE TABLE product (
    prod_no        NUMBER(7) NOT NULL,
    prod_desc      VARCHAR2(50) NOT NULL,
    prod_unitprice NUMBER(7, 2) NOT NULL,
    prod_category  VARCHAR2(20),
    product_id     NUMBER NOT NULL
);

COMMENT ON COLUMN product.prod_no IS
    'Product number';

COMMENT ON COLUMN product.prod_desc IS
    'Product Description';

COMMENT ON COLUMN product.prod_unitprice IS
    'product unit price';

COMMENT ON COLUMN product.prod_category IS
    'product category';

ALTER TABLE product ADD CONSTRAINT product_pk PRIMARY KEY ( product_id );

-- Error - Unique Constraint PRODUCT.PRODUCT_PKv1 doesn't have columns

ALTER TABLE orders
    ADD CONSTRAINT customer_orders FOREIGN KEY ( cust_no )
        REFERENCES customer ( cust_no );

ALTER TABLE orderline
    ADD CONSTRAINT orders_orderline FOREIGN KEY ( order_no )
        REFERENCES orders ( order_no );

ALTER TABLE orderline
    ADD CONSTRAINT product_orderline FOREIGN KEY ( product_id )
        REFERENCES product ( product_id );

-- Error - Foreign Key PRODUCT_ORDERLINEv1 has no columns

CREATE SEQUENCE product_product_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER product_product_id_trg BEFORE
    INSERT ON product
    FOR EACH ROW
    WHEN ( new.product_id IS NULL )
BEGIN
    :new.product_id := product_product_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              8
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0

SPOOL off
set echo off